### ISSUE TITLE
Potenitally shorter

### ISSUE THREAD

**Issue by GrosSacASac** [feross/fromentries#12]
Using array de-structuring:
```
 function fromEntries2 (iterable) {
  return [...iterable]
    .reduce((obj, [key, val]) => Object.assign(obj, { [key]: val }), {})
}
```

Using array de-structuring and comma operator: 
```
function fromEntries3 (iterable) {
  return [...iterable]
    .reduce((obj, [key, val]) => (obj[key] = val, obj), {})
}
```

Thoughts ?

**Comment by antonk52** [comment]
A bit of a lame set up but using manual assignment can be [more performant](https://jsperf.com/fromentries/1) as well

**Comment by feross** [comment]
Thanks for the suggestion. I don't want to make the code too tricky to understand just to save a few bytes and the comma trick is a bit too tricky IMO :)

**Comment by jimmywarting** [comment]
> I don't want to make the code too tricky to understand just to save a few bytes and the comma trick is a bit too tricky IMO

me neither, but it's fun to code golf and try to come up with the shortest possible solution.

How about this one?
```js
export default c=>([...c].map(([a,b])=>c[a]=b,c={}),c)
```
