### ISSUE TITLE
Arrow function to `function`?

### ISSUE THREAD

**Issue by acagastya** [feross/fromentries#18]
Arrow functions were a ES6 feature and are not supported in older versions of Safari.  ([For reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility)).  Please consider changing the arrow function to the older function definition.

**Comment by feross** [comment]
Sorry – Safari 10 was released in 2016 and I don't want to support it in this project.

**Comment by acagastya** [comment]
Okay, all right, @feross.  But please consider just five bytes more will increase the support to many more browsers where the system is stuck in the legacy code.  Safari 10 was just an example.
